version: "3.5"

services: 
  mysql:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes: 
      - ./data:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
    ports: 
      - "3306:3306"
  
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports: 
      - "6379:6379"